spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6642/main
spring.datasource.username=dbuser
spring.datasource.password=12345

server.port=8080

client.url=http://localhost:9090