CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
    );


CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation  BOOLEAN NOT NULL DEFAULT TRUE,
    state  VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    CONSTRAINT fk_events_category
       FOREIGN KEY (category_id)
       REFERENCES categories (id),
    CONSTRAINT fk_events_initiator
       FOREIGN KEY (initiator_id)
       REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT uq_title UNIQUE (title)
    );

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_comp_events_compilation
        FOREIGN KEY (compilation_id)
        REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_comp_events_event
        FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE
    );
